license_id: "hdx-other"
license_other: "Scientific Use License. See [terms of use](https://microdata.unhcr.org/index.php/terms-of-use) for details."
caveats: "The data must be requested via the resource download link"
private: False
